spring:
  cloud:
    nacos:
      discovery:
        server-addr: 218.78.33.135:8848
      config:
        server-addr: 218.78.33.135:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: msg
          uri: lb://msg
          predicates:
            - Path=/msg/**
          filters:
            - StripPrefix=1
        - id: msg-websocket
          uri: ws://localhost:1324
          predicates:
            - Path=/channel/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:1025/auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    host: 218.78.33.135        # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: mbfczzzz              # Redis服务器连接密码（默认为空）
    timeout: 10000
    lettuce:
      pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          max-idle: 8
#      cluster:
#        refresh:
#          adaptive: true
      shutdown-timeout: 100
#    cluster:
#      nodes:
#        - 106.13.17.32:6371
#        - 106.13.17.32:6372
#        - 106.13.17.32:6373
#        - 106.13.17.32:6374
#        - 106.13.17.32:6375
#        - 106.13.17.32:6376

secure:
  ignore:
    urls:
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/channel/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/user/login"
      - "/user/loadByUsername"
      - "/user/register"
      - "/user/oss/policy"
      - "/user/oss/callback"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:

